common: &common
  :hash_secret: 1yQLt4UOTF1UXB5QNYr3//T4E3CeXDXh6GO9MbI1cWxaXciTZQvUdqe6QMwYzG6eUM9emp3podeL/Rm2kpi04c/M7460ms3JMTf8pwV6Qv+JBAWzdnn/8Wpc6EqYT08UC7OrGHm2GbgsB67GtYnKySlqKYT/LTTtVSPvbTgxXhA=
  :styles: 
    :normal_fill: "1160x564#"
    :normal_fit: "1160x564"
    :thumbnail_fill: "468x316#"
    :thumbnail_fit: "468x316"
  :default_url: "/files/:style/missing.png"
  
local: &local
  <<: *common
  :path: ":rails_root/public/system/:id_partition/:hash.:extension"
  :url: "/system/:id_partition/:hash.:extension"
  
remote: &remote
  <<: *common
  
development:
  <<: *local

production:
  <<: *remote
