common: &common
  :hash_secret: 1yQLt4UOTF1UXB5QNYr3//T4E3CeXDXh6GO9MbI1cWxaXciTZQvUdqe6QMwYzG6eUM9emp3podeL/Rm2kpi04c/M7460ms3JMTf8pwV6Qv+JBAWzdnn/8Wpc6EqYT08UC7OrGHm2GbgsB67GtYnKySlqKYT/LTTtVSPvbTgxXhA=
  :styles: 
    :normal_fill: "1160x564#"
    :normal_fit: "1160x564"
    :thumbnail_fill: "468x316#"
    :thumbnail_fit: "468x316"
  :default_url: "/files/:style/missing.png"
  
local: &local
  <<: *common
  :path: ":rails_root/public/system/:id_partition/:hash.:extension"
  :url: "/system/:id_partition/:hash.:extension"
  
remote: &remote
  <<: *common
  # :storage: :s3
  # :url: ":s3_domain_url"
  # :path: ":db_tenant/:class/:attachment/:id_partition/:style/:hash.:extension"
  # :s3_host_name: s3-ap-southeast-2.amazonaws.com
  # :s3_credentials:
  #   :access_key_id: AKIAI7WICS3X2JBONXSA
  #   :secret_access_key: 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
  
development:
  <<: *local

production:
  <<: *remote
  # :bucket: prod.listed.real-estate
